version: "3.3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - 13bhai-backend
  13bhai-backend:
    image: rounaksingh1694/13bhai-backend
    volumes:
      - ./:/app:ro
      - /app/node_modules
